version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.14.2

jobs:
  build-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            echo "building aaronreynoza/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG"
            docker build -t aaronreynoza/shopmate:0.1.0 .
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install libraries
          command: | 
            cd backend && npm ci
      - run:
          name: "Run tests"
          command: |
            cd backend && npm run test
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install libraries
          command: | 
            cd backend && npm ci
      - run:
          name: "Run lint"
          command: |
            cd backend && npm run lint
  build-backend:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install libraries
          command: | 
            cd backend && npm ci
      - run:
          name: "Compile backend"
          command: |
            cd backend && npm run build
  build-frontend:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install libraries
          command: | 
            cd frontend && npm ci
      - run:
          name: "Compile frontend"
          command: |
            cd frontend && npm run build

workflows:
  version: 2
  core:
    jobs:
      - test
      - lint
      - build-backend:
          requires:
            - test
            - lint
      - build-frontend:
          requires:
            - test
            - lint
      - build-image:
          requires:
            - build-backend
            - build-frontend
